- R/dal.R
- man/extract_country_data.Rd
Introduced several features to `extract_country_data()`:
1. Handling of spatial file errors are more explicit and programmatic. This is resolves issue #73.
2. Removed requirement of a `.raw.data` to contain spatial files before `extract_country_data()` can run. This resolves issue #71.
3. Included prov and country population datasets to the output of `extract_country_data()`. This resolves issue #69.
> 71 remove spatial requirement extract_country_data()

- R/f.stool.ad.01.R
those without AFP cases should not have a stool adequacy of 0
> 🐛 f.stool.ad.01() NA for geography without AFP cases

- R/dr.afp.functions.R
- R/dr.figure.functions.R
- R/dr.lab.functions.R
- R/dr.main.functions.R
- R/f.color.schemes.R
- R/globals.R
This pull request enhances the functions `generate_ctry_timeliness_graph()` and `generate_prov_timeliness_graph()` to show additional subinterval data. Changes were made to the lab cleaning script for both WHO and regional lab data so it can handle the recent changes in the code.
Additionally, this pull request has a critical update on local lab data loading. The change fixes a bug where lab data is not loaded when a local lab path is designated during `init_dr`, if lab data already exists in the `data` folder within the desk review folder of a country.
> ❇️ additional subinterval data calculated for WHO lab data

- R/dal.R
to test create a plot and a flextable and write it to edav from R. for non gg or flextable objects specify a non-rds or csv file from your local and upload
ex.
edav_io(io = "write", obj = plot, file_loc = "sia_impact_test/plot.png")
edav_io(io = "write", obj = flex, file_loc = "sia_impact_test/flex.png")
edav_io(io = "upload", file_loc = "sia_impact_test/report.html", 
local_path = "C:/Users/uic3/Desktop/gitrepos/core-2.0/sia_impact_pipeline/reports/SIA Impact Report_FULL_2024-10-02.html")
> 127 add ability to write png files to edav io

- R/dal.R
load_clean spatial functions now contain an additional parameter, version. options are "standard" or "dev", standard is default. 
to test please use the functions to pull the standard and dev shape files and compare, there are more provinces/districts in the dev shapefiles and the dev shapefiles contain 2 extra variables, "AREA_SQM" and "LENGTH_M" 
you can check this adm2guid {BDB536A7-CA9D-439F-9CF7-F7EFF5D8A23E} in the district files, it should be in the dev shapes but not the standard shapes
> 137 add spatial dev option to load clean spatials

- R/dr.figure.functions.R
- man/generate_afp_case_map.Rd
- man/generate_es_det_map.Rd
- man/generate_iss_map.Rd
- man/generate_npafp_maps.Rd
- man/generate_npafp_maps_dist.Rd
- man/generate_pop_map.Rd
- man/generate_stool_ad_maps.Rd
- man/generate_stool_ad_maps_dist.Rd
- man/generate_timeliness_maps.Rd
Previously, maps had used only the most recent shape files when creating maps. However, shape files from the most recent year may be different from the previous year. I revised the mapping functions so that years are now matching up to the correct shapefiles.
To test, run a desk review of Somalia (or any country with shape changes in the past 4 years). Only requirement would be to run the cleaning function for `ctry.data` and to load the spatial files like so:
```
ctry.shape <- load_clean_ctry_sp(ctry_name = Sys.getenv("DR_COUNTRY"), type = "long")
prov.shape <- load_clean_prov_sp(ctry_name = Sys.getenv("DR_COUNTRY"), type = "long")
dist.shape <- load_clean_dist_sp(ctry_name = Sys.getenv("DR_COUNTRY"), type = "long")
```
> ❇️ Desk review mapping functions now use long spatial data

- R/dr.lab.functions.R
Relates to #140 
In some instances, the geomatching algorithm will explode the regional lab dataset, taking a dataset that may have 5000 rows to 10000+ rows. This fix ensures this doesn't happen. To test, run a desk review using regional lab data. Check the number of lab data before cleaning and after cleaning
> 🐛 Update geomatching algorithm when cleaning regional lab data 

- R/dal.R
changed sia.rounds to only include ID vars: sia and subactivity codes, start date, vax type, and locations adm0-2 names and GUIDs + cluster vars
can be tested in the same way that the previous PR for sia.rounds was
> refactor sia.rounds in raw.data and make cdc variables explicit

- R/f.npafp.rate.01.R
- man/f.npafp.rate.01.Rd
New parameter added called `missing_agemonths`. To test, run `f.npafp.rate.01()` per usual using either `raw.data` or `ctry.data`. 
Closes #169
> ❇️ Add flag for missingness of `age.months` in `f.npafp.rate.01()`

- R/f.npafp.rate.01.R
- R/f.stool.ad.01.R
Closes #211 
To test, run both functions using `raw.data`. Note that the function will have different number of rows, with the stool adequacy summary table having more. Perform a `setdiff()` on the adm2guids on both outputs and confirm that one of the adm2guid in the stool table is not present because 1) it is not a pending nor an NPAFP case 2) age is not <180 months.
> 🐛 `f.npafp.rate.01` and `f.stool.ad.01` don't have matching spatial groupings

- R/dr.figure.functions.R
- man/generate_inad_tab.Rd
I actually took out the argument on sirfunction v.1.2.0, but did not update the example or set a deprecation warning.
#Closes 182
> 🐛  Update deprecation message and example for `generate_inad_tab()`

- R/dal.R
- sirfunctions.Rproj
Navigate to an empty folder on EDAV. When you prompt to select a folder (option 2), it should automatically send a warning that the current folder is empty and there's nothing to navigate to.
To test, call `explore_edav()` and go to `Data/desk_review/empty_folder` and select option 2.
> 258 explore edav fix

- R/f.npafp.rate.01.R
- R/f.stool.ad.01.R
- R/f.timely.detection.01.R
- man/f.npafp.rate.01.Rd
- man/f.stool.ad.01.Rd
- man/f.timely.detection.01.Rd
`f.npafp.rate.01()` didn't have an example before. It looks like the other core functions already had examples, so it was the only function missing one.
> ❇️ Add examples for f.npafp.rate.01()

- R/dal.R
- R/dr.main.functions.R
- man/generate_data.Rd
- man/init_dr.Rd
- man/update_data.Rd
The only aspect of the desk review code that uses EDAV resources is during `init_dr()` as it calls for `get_all_polio_data()`. I've added three parameters to `init_dr()`: `data_folder, polis_folder, use_edav`. These parameters are used within `get_all_polio_data()` to determine whether we should use processed data from EDAV or locally to build `raw_data`. 
To test, run:
```
ctry_data <- init_dr("algeria", 
"2023-01-01",
"2025-04-30",
local_dr_folder = "C:/Users/XRG9/Desktop/local_dr", # folder that contains dr runs
data_folder = "C:/Users/XRG9/Desktop/data_folder", # folder that contains the analytics folder
polis_folder = "C:/Users/XRG9/Desktop/polis_data", # folder containing POLIS data
use_edav = F) 
```
> ❇️ Allow `init_dr()` to work locally

- .gitignore
- R/dal.R
- man/create_polis_data_folder.Rd
- man/edav_io.Rd
- man/get_all_polio_data.Rd
This PR adds `archive` and `keep_n_archives` arguments to `get_all_polio_data()`, like in `tidypolis::preprocess_cdc()`.
This helps avoid saving large files when running locally.
Closes #315
> ❇️  315 make archiving optional in get_all_polio_data

- DESCRIPTION
- R/dal.R
- R/sirfunctions-package.R
Note: must download arrow package first before testing.
To test, use the typical edav_io read and write functionalities. You can read the example iris parquet dataset located in Sandbox/iris.parquet. 
Also, test out sirfunctions_io() to make sure it works as intended. To test:
1. sirfunctions_io("write", NULL, file_loc = "path/to/downloads/folder/iris.parquet", obj = iris, edav = F)
2. sirfunctions_io("read", NULL, file_loc = "path/to/downloads/folder/iris.parquet", obj = iris, edav = F)
> ❇️ Add ability to read and write parquet files from edav io

- DESCRIPTION
- R/dal.R
- man/get_all_polio_data.Rd
This PR adds support for specifying output format in `get_all_polio_data()` and handling `.qs` nd `.qs2` format in `sirfunctions_io()`
closes #328
> 328 add support for specifying output format in get all polio data and handling qs format in sirfunctions io

- R/kpi.main.functions.R
Added a filter to exclude cases where place.admin.0 is 'INDIA' and ctry.short is 'CHN'. Replaced cli_abort with cli_alert_warning and added printing of non-unique country abbreviations for better debugging.
> Improve country abbreviation filtering and warnings

- R/dal.R
- man/get_constant.Rd
Removed 'AFRO_LAB_DATA' and 'EMRO_LAB_DATA' from the list of available constants and updated the values for 'SIRFUNCTIONS_GITHUB_TREE' and 'CLEANED_LAB_DATA'. Updated the documentation in get_constant.Rd to reflect these changes.
Closes #369 
To test, run:
```
get_constant("CLEANED_LAB_DATA")
```
> Update constants in get_constant and documentation

- R/dal.R
- man/read_excel_from_edav.Rd
The `read_excel_from_edav()` function now accepts a 'sheet' parameter to allow reading a specific sheet by name or index. Documentation and usage have been updated to reflect this change, and the function now handles both .xlsx and .xls files when reading all sheets. This is an internal function used in `edav_io()`.
To test:
```
check <- edav_io("read", file_loc = "Data/lab/2025-08-29 AFRO Lab Extract (AFP only since 2022).xlsx", sheet = 1)
check <- edav_io("read", file_loc = "Data/lab/2025-08-29 AFRO Lab Extract (AFP only since 2022).xlsx", sheet = "Data Dictionary")
check <- edav_io("read", file_loc = "Data/lab/2025-08-29 AFRO Lab Extract (AFP only since 2022).xlsx")
```
Closes #363
> Add sheet selection to read_excel_from_edav

- R/dr.lab.functions.R
- man/clean_lab_data.Rd
- man/clean_lab_data_regional.Rd
- man/get_lab_locs.Rd
Introduces a use_edav argument to clean_lab_data, clean_lab_data_regional, and get_lab_locs, allowing users to control whether lab location data is downloaded from EDAV or loaded from a local file. Updates documentation accordingly and improves error handling for missing lab location files.
Closes #366 
To test:
First download the lab testing locations file (will give this to you directly)
```
lab_data <- sirfunctions::edav_io(file_loc = get_constant("CLEANED_LAB_DATA"))
lab_data_cleaned <- clean_lab_data(lab_data, "2024-01-01", "2024-12-31")
lab_data_cleaned <- clean_lab_data(lab_data, "2024-01-01", "2024-12-31", use_edav = F)
lab_data_cleaned <- clean_lab_data(lab_data, "2024-01-01", "2024-12-31", use_edav = F, lab_locs_path = "C:/path/to/lab_locs.csv")
```
> Add use_edav parameter to lab data functions
