DESCRIPTION, R/f.npafp.rate.01.R, R/f.stool.ad.01.R, R/f.timely.detection.01.R, R/globals.R, man/f.npafp.rate.01.Rd, man/f.stool.ad.01.Rd
Updated package with patch to change var reference from `cdc.classification.all2` to `cdc.classification.all`
=> Core syntax update

R/dal.R
adding a metadata object to raw.data pull from get_all_polio_data
=> 16 - Raw.data - metadata - object

README.md
- Set up github flow and added basic release documentation to README
=> closes #28 #27

R/dal.R
Fixed issue by specifying which token to use for storage resources
=> :bug: fixed edav_io token specification closes #33

R/com.R, R/dal.R
Didn't see a lot of functionality for reading from sharepoint but can do that as well.
=> Comms functions for sharepoint and teams 

R/dal.R
=> :sparkle: added metadata vdpv class change date tag - closes #39

R/com.R
=> :sparkle: added email function, closes #23

R/dal.R
Added in features to be able to create directories and to check if specific directories exist. Closes #45
=> Added `create` and `exists` functions to `edav_io()`

R/dal.R
=> Added features to export container function and added exists features in edav_io

DESCRIPTION, R/dal.R
`extract_country_data()` was using raw.data, which isn't a locally defined variable inside the function. Changed all reference to `raw.data` to `.raw.data`
=> 75 extract country data fixing raw.data

R/f.color.schemes.R, man/f.color.schemes.Rd
Added color schemes used in the desk reviews but aren't currently in `f.color.schemes()`
=> 80 additional color schemes

R/create_emergence_group_gif.R
=> Add function to visualize spread of emergences

R/f.npafp.rate.01.R
needed to add a filter to only include U15 for the numerator
=> 99-npafp-func-hotfix

R/dr.afp.functions.R, R/dr.es.functions.R, R/dr.excel.export.functions.R, R/dr.figure.functions.R, R/dr.lab.functions.R, R/dr.pop.functions.R, R/dr.powerpoint.functions.R
Please see #108 for the list of issues addressed in this pull request.
=> 🐛 .data references in tidyselect operations

R/dal.R
Relates to #65 
To test, download [pngquant](https://pngquant.org/) first.
=> ❇️ Compress plot images function

R/dal.R
needed to remove virus.id from duplicate checking in duplicate_check function. 
to tet just run get_all_polio_data and check for presence of pos.dupe in raw.data
=> update pos dupe check, closes #147

DESCRIPTION, R/dr.afp.functions.R, R/dr.lab.functions.R
Relates to #141. To test, this requires two datasets: WHO lab data and regional lab data. Regional lab data is found on EDAV. WHO lab data is typically what Liz sends to us - ask Mervin for this dataset when getting ready to review. To test, take any of the previous desk reviews from the Desk Review folder and run a desk review. Test on Algeria
=> 🐛 Include lab intervals for regional lab data

DESCRIPTION, R/dr.afp.functions.R, R/dr.lab.functions.R
Bug fixes for the following:
#143 🐛 Include lab intervals for regional lab data
#144 🐛 Update geomatching algorithm when cleaning regional lab data
=> Bug fixes for lab cleaning and generating lab timeliness intervals using lab data

R/dal.R
this fix will more explicitly take the file extension of datasets on EDAV and read/write them appropriately
to test you can run the code below. I've put a 2 csv and 1 rds file in polis_test to be read/written/archived. Make sure that the 3 files are removed from 'CORE_ready_files' and are present in the appropriate archive folder 
library(tidypolis)
init_tidypolis("POLIS_test", edav = T)
polis_data_folder = Sys.getenv("POLIS_DATA_CACHE")
ts <- Sys.time()
timestamp <- paste0(lubridate::date(ts),"_",lubridate::hour(ts),"-",lubridate::minute(ts),"-",round(lubridate::second(ts), 0))
#create directory
#files in directory
c(
file.path(polis_data_folder, "Core_Ready_Files"),
file.path(polis_data_folder, "Core_Ready_Files", "Archive"),
file.path(polis_data_folder, "Core_Ready_Files", "Archive", …
=> convert read/write grepls to endsWith

DESCRIPTION, R/dal.R, R/f.color.schemes.R
This pull request is to implement the following bug fixes into main.
#177 
#202
=> sirfunctions v1.2.1

DESCRIPTION, R/f.stool.ad.01.R, man/f.stool.ad.01.Rd
Adds a patch from hotfix to close #211.
=> 🐛 geographic aggregation of stool adequacy and npafp functions not aligned.

R/dr.iss.functions.R, man/clean_iss_data.Rd, man/iss_data_errors.Rd
To test, run the two functions on the ISS data located on `GID/PEB/SIR/Data/desk_review/iss_data_examples`
Closes #184
=> ❇️ Run `clean_iss_data()` and `iss_data_errors()` outside of ctry.data

R/dal.R, man/load_clean_ctry_sp.Rd, man/load_clean_dist_sp.Rd, man/load_clean_prov_sp.Rd
Closes #155 
Replaced any parameters using `.` with `_` to ensure consistency within parameter names. Also added `prov_name` and `dist_name` parameters to `load_clean_dist_sp()`.
=> ❇️  `load_clean_sp` functions additional formatting for arguments

vignettes/kpi-analysis.Rmd
Please see the vignette and review. Knit it and if there are changes feel free to commit directly.
=> ❇️ Vignette to run the kpi analysis

R/dr.afp.functions.R, R/dr.excel.export.functions.R, R/dr.figure.functions.R, R/dr.lab.functions.R, R/generate_adhoc_map.R, man/generate_lab_timeliness.Rd
Closes
To test 322, run the following and make sure the flextable doesn't contain a "weight" column.
```
raw_data <- get_all_polio_data()
ctry_data <- extract_country_data("tunisia", raw_data)
cstool <- f.stool.ad.01(
afp.data = ctry.data$afp.all.2,
pop.data = ctry.data$ctry.pop,
start.date = start_date,
end.date = end_date,
spatial.scale = "ctry",
missing = "good",
bad.data = "inadequate",
rolling = F,
sp_continuity_validation = F
)
inad.tab.flex <- generate_inad_tab(ctry.data, cstool, start_date, end_date) 
```
To test 321, run the following and make sure the Excel tabs are labelled "stoolad" instead of NPAFP.
```
dstool <- f.stool.ad.01(
afp.data = ctry.data$afp.all.2,
pop.data = ctry.data$dist.pop,
start.date = start_date,
end.date = end_date,
spatial.scale = "dist",
missing = "good", …
```
=> 🐛 Fix lab interval calculations and the adhoc map

DESCRIPTION, R/dal.R
Implements fix to get Posit Connect to work with sirfunctions #338
=> sirfunctions patch v2.0.1
